kubectl -n staging get deploy,po,svc,pvc
NAME                              READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/order-service     2/2     2            2           6h31m
deployment.apps/postgres          1/1     1            1           13s
deployment.apps/product-service   2/2     2            2           58m

NAME                                  READY   STATUS    RESTARTS   AGE
pod/order-service-6f54f5fdf7-kqkxz    1/1     Running   0          85m
pod/order-service-6f54f5fdf7-lfnj6    1/1     Running   0          85m
pod/postgres-878767df8-f65d9          1/1     Running   0          13s
pod/product-service-d785cb554-5dvdv   1/1     Running   0          12m
pod/product-service-d785cb554-j6h2t   1/1     Running   0          12m

NAME                      TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE
service/order-service     NodePort    10.100.92.143   <none>        3002:30699/TCP   6h30m
service/postgres          ClusterIP   10.103.53.179   <none>        5432/TCP         13s
service/product-service   NodePort    10.108.64.139   <none>        3001:30604/TCP   58m

NAME                                  STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   VOLUMEATTRIBUTESCLASS   AGE
persistentvolumeclaim/postgres-data   Bound    pvc-5c2df019-0b71-4daa-94f5-ae02640cfd89   2Gi        RWO            standard       <unset>                 13s